require 'extensions/scraper/models/skeleton/order'
require 'extensions/scraper/models/skeleton/page'
require 'extensions/scraper/models/skeleton/activity'
require 'extensions/scraper/models/skeleton/user'
require 'extensions/scraper/models/skeleton/assignation'
require 'extensions/scraper/models/skeleton/movement'
